// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkerService.Data;

#nullable disable

namespace WorkerService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240819190940_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.NetworkPacket", b =>
                {
                    b.Property<string>("DestinationIp")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DestinationPort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourcePort")
                        .HasColumnType("int");

                    b.HasKey("DestinationIp");

                    b.ToTable("NetworkPackets");
                });
#pragma warning restore 612, 618
        }
    }
}
